//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\DEMO\App\App\CrystalReportFile.
        /// </summary>
        internal static string CrystalReportsFilePath {
            get {
                return ResourceManager.GetString("CrystalReportsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1#0#1#1#1#1#1#1#1.
        /// </summary>
        internal static string DischargeProcess {
            get {
                return ResourceManager.GetString("DischargeProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:DMS.
        /// </summary>
        internal static string DMSRootDirectoryPath {
            get {
                return ResourceManager.GetString("DMSRootDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string EnableAutoRegistrationCharges {
            get {
                return ResourceManager.GetString("EnableAutoRegistrationCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varanasi.
        /// </summary>
        internal static string HospitalAddress {
            get {
                return ResourceManager.GetString("HospitalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string HospitalCode {
            get {
                return ResourceManager.GetString("HospitalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9621000017.
        /// </summary>
        internal static string HospitalContact1 {
            get {
                return ResourceManager.GetString("HospitalContact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HospitalContact2 {
            get {
                return ResourceManager.GetString("HospitalContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GWS@gmail.com.
        /// </summary>
        internal static string HospitalEmail {
            get {
                return ResourceManager.GetString("HospitalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCABvAL0DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HospitalLogo {
            get {
                return ResourceManager.GetString("HospitalLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity Web Solutions.
        /// </summary>
        internal static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.GWS.com.
        /// </summary>
        internal static string HospitalWesite {
            get {
                return ResourceManager.GetString("HospitalWesite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string MaxAllowedDocumentSizeInMB {
            get {
                return ResourceManager.GetString("MaxAllowedDocumentSizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1#0#1.
        /// </summary>
        internal static string OpdCosultationProcess {
            get {
                return ResourceManager.GetString("OpdCosultationProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1#1#0#0#1#1.
        /// </summary>
        internal static string PathologyProcess {
            get {
                return ResourceManager.GetString("PathologyProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientDocuments.
        /// </summary>
        internal static string PatientDocumentFolderName {
            get {
                return ResourceManager.GetString("PatientDocumentFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientImages.
        /// </summary>
        internal static string PatientImageFolderName {
            get {
                return ResourceManager.GetString("PatientImageFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1#1#1.
        /// </summary>
        internal static string Radiologyrocess {
            get {
                return ResourceManager.GetString("Radiologyrocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40939.
        /// </summary>
        internal static string RegistrationChargesServiceId {
            get {
                return ResourceManager.GetString("RegistrationChargesServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365.
        /// </summary>
        internal static string RegistrationChargesValidityInDays {
            get {
                return ResourceManager.GetString("RegistrationChargesValidityInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UserCorporateMappingEnabled {
            get {
                return ResourceManager.GetString("UserCorporateMappingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string UserRoomMappingEnabled {
            get {
                return ResourceManager.GetString("UserRoomMappingEnabled", resourceCulture);
            }
        }
    }
}
